"""
Django settings for Egresados project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n=g1vfl8m54(awna+=n8yb$$-xldekb4)_$d=(1*p+dcb8&m&='

#Local
RECAPTCHA_PUBLIC_KEY = '6LdaUqcUAAAAAOK3xzjo-oknTM33fbXExlcwFG0z'
RECAPTCHA_PRIVATE_KEY = '6LdaUqcUAAAAANtBkskWrDSPz2SezQT_i3jsSRon'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#-->DEBUG= False

ALLOWED_HOSTS = []

#-->ALLOWED_HOSTS = ['ObservatorioUTP.pythonanywhere.com', 'localhost', '127.0.0.1']

AUTHENTICATION_BACKENDS=['app_core.backends.SuperUserBackend','app_core.backends.AdminBackend', 'app_core.backends.EgresadoBackend']



# Application definition

INSTALLED_APPS = [
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_core.apps.AppCoreConfig',
    'app_registrarse.apps.AppRegistrarseConfig',   
    'captcha',
    'ckeditor',
    'perfiles',
    'messenger',
    'cities_light',
    'contenido.apps.ContenidoConfig',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Egresados.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.template.context_processors.request',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'Egresados.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join (BASE_DIR, 'staticfiles')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'observatorioutpe@gmail.com'
EMAIL_HOST_PASSWORD = 'Pereira2019'
EMAIL_PORT = '587'
EMAIL_USE_TLS   = True

#Media files
MEDIA_URL = '/media/'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL='app_core.User'

#LOGIN_REDIRECT_URL=''

LOGOUT_REDIRECT_URL='/login/'

CITIES_LIGHT_APP_NAME= 'app_core'

"""
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
        ],
        'height': 300,
        'width': 'auto',
    }
}

"""
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 'auto',
         'extraPlugins': ','.join(['youtube']),
    },
}
"""


CKEDITOR_CONFIGS = {
   'default': {
       'toolbar': 'full',
       'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image','Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList'],
            ['Indent','Outdent'],
            ['Maximize'],
        ],
        'extraPlugins': ','.join(['video', 'youtube', 'justify','liststyle','indent']),
        'height': 300,
        'width': 'auto',
   },
}
"""
CKEDITOR_UPLOAD_PATH = 'uploads/'