# Generated by Django 2.2 on 2019-07-13 16:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
