# Generated by Django 2.2 on 2019-06-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='Tipo_de_identificacion',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='egresado',
            name='Tipo_de_identificacion',
        ),
        migrations.AddField(
            model_name='user',
            name='DNI',
            field=models.CharField(default='', max_length=10, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='user',
            name='Tipo_de_identificacion',
            field=models.CharField(default='Cédula de ciudadania', max_length=20, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.Country'),
        ),
    ]
