# Generated by Django 2.2 on 2019-06-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_auto_20190626_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='ciudad',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Tipo_de_identificacion',
            field=models.CharField(choices=[['Cédula de ciudadania', 'Cédula de ciudadania'], ['Pasaporte', 'Pasaporte']], default='Cédula de ciudadania', max_length=20, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(choices=[['WW', 'WWW']], default='WWW', max_length=30, verbose_name='Pais'),
        ),
    ]
