# Generated by Django 2.2 on 2019-06-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20190628_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(default='', max_length=30, verbose_name='Pais'),
        ),
    ]
