# Generated by Django 2.2 on 2019-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20190629_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(default='', max_length=30, verbose_name='Ciudad'),
        ),
    ]
