# Generated by Django 2.2 on 2019-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_auto_20190630_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='activacion',
            field=models.BooleanField(default=False, verbose_name='Activacion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_restablecimiento',
            field=models.CharField(blank=True, default='', max_length=180, null=True, verbose_name='Id Recuperacion'),
        ),
    ]
