# Generated by Django 2.2 on 2019-07-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_auto_20190703_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='ciudad_p',
            field=models.BooleanField(default=True),
        ),
    ]
