# Generated by Django 2.2 on 2019-07-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_circulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='activacion',
            field=models.BooleanField(default=False, verbose_name='Activacion'),
        ),
    ]
