# Generated by Django 2.2 on 2019-07-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__nombres'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfil'},
        ),
    ]
