# Generated by Django 2.2 on 2019-07-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registrarse', '0002_auto_20190703_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
